name: Padavan Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone padavan-ng
      run: |
        git clone https://gitlab.com/hadzhioglu/padavan-ng.git padavan

    - name: Custom scripts (zapret)
      run: |
        cd padavan/trunk/user
        git clone https://github.com/bol-van/zapret.git

        # УРЕЗАЕМ zapret
        sed -i 's/ENABLE_QUIC=1/ENABLE_QUIC=0/g' zapret/config
        sed -i 's/ENABLE_IPV6=1/ENABLE_IPV6=0/g' zapret/config

    - name: Copy config
      run: |
        cp config/TL_WR841N.config padavan/trunk/configs/templates/TPLINK_TL_WR841N-V13.config

    - name: Build firmware
      run: |
        cd padavan/trunk
        chmod +x build_firmware.sh
        ./build_firmware.sh TPLINK_TL_WR841N-V13

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: padavan/trunk/images/*
